language: elixir
elixir:
  - 1.4.1
addons:
  postgresql: '9.4'
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
  - psql -c "create database cms"
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json, credo --strict
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

